### ISSUE TITLE
Feature request: define per-server outgoing addresses

### ISSUE THREAD

**Issue by x-qq** [niklata/muonsocks#2]
Right now it is possible to specify multiple listen addresses by providing multiple `-i` options, but all of the client threads will reuse the same bind address for outgoing address (provided by `-b` option). 

In a situation where a proxy server has multiple network interfaces, it would be nice to be able to specify multiple outgoing addresses so that a user connecting to a specific `-i` address could have his outgoing connections routed through a specific outgoing `-b` address.

This could be acheived with something as simple as specifying multiple `-i` and `-b` options on the command line, with outgoing addresses being assigned to the listen addresses in order in which they are specified, so that in this example:

```
./muonsocks -i 192.168.1.1 -i 10.0.0.1 -b 192.168.1.2 -b 10.0.0.10 -p 1080
```

connections made to 192.168.1.1:1080 use 192.168.1.2 for their outgoing connections, and connections made to 10.0.0.1 use 10.0.0.10

**Comment by niklata** [comment]
I handle a similar situation by running multiple muonsocks processes, one per outgoing interface, and each running as a different uid on the server.  But I will look at the structure of muonsocks and if it isn't too invasive to do so, I will add a mapping from input addresses to output addresses.

**Comment by niklata** [comment]
I'd prefer not to add such a mapping unless there's a reason why running multiple muonsocks processes can't handle this case.  It has the advantage of allowing mappings by port->outgoing IP as well as address->outgoing IP, too.

Please feel free to reopen if there's a good reason why multiple processes can't handle these use cases.
